version: '3.8'

services:
 web:
  build:
   context: ./
  ports:
  - 8200:8000
  volumes:
  - ./financial:/app/financial
  - ./migrations:/app/migrations
  env_file: .env
  depends_on:
  - db
 
 db:
  image: postgres:15-alpine
  volumes:
  - postgres_data:/var/lib/postgresql/data/
  ports:
  - 5432:5432
  environment:
  - POSTGRES_USER=financial_api
  - POSTGRES_PASSWORD=financeial_pstgr_pass
  - POSTGRES_DB=financial_db

volumes:
  postgres_data: